/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg40.views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import pkg40.controllers.EmployeeController;
import pkg40.models.Employee;

/**
 *
 * @author asus
 */
public class EmployeeView extends javax.swing.JFrame {

    EmployeeController ec;
    
    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() throws SQLException {
        initComponents();
        this.ec = new EmployeeController();
        employeeTable.setModel(loadData(""));
        setWidthColumn();
    }
    
    public void setWidthColumn(){ 
        TableColumn column;
        employeeTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = employeeTable.getColumnModel().getColumn(0); 
        column.setPreferredWidth(30);
        column = employeeTable.getColumnModel().getColumn(1); 
        column.setPreferredWidth(75); 
        column = employeeTable.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = employeeTable.getColumnModel().getColumn(3); 
        column.setPreferredWidth(100); 
        column = employeeTable.getColumnModel().getColumn(4); 
        column.setPreferredWidth(150); 
        column = employeeTable.getColumnModel().getColumn(5); 
        column.setPreferredWidth(150); 
        column = employeeTable.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100); 
        column = employeeTable.getColumnModel().getColumn(7); 
        column.setPreferredWidth(75); 
        column = employeeTable.getColumnModel().getColumn(8); 
        column.setPreferredWidth(75);
        column = employeeTable.getColumnModel().getColumn(9); 
        column.setPreferredWidth(75); 
        column = employeeTable.getColumnModel().getColumn(10); 
        column.setPreferredWidth(75); 
        column = employeeTable.getColumnModel().getColumn(11); 
        column.setPreferredWidth(75); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        buttonSearch = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        employeeTable.setAlignmentX(1.0F);
        jScrollPane1.setViewportView(employeeTable);

        buttonSearch.setText("search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        refreshButton.setText("refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSearch)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton)
                    .addComponent(buttonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        if(searchTextField.getText().equals("")){
            buttonSearch.disable();
        }else
                try {
            // TODO add your handling code here:
            employeeTable.setModel(loadData(searchTextField.getText()));
//        regionTable.setModel(loadData(stringTextField.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try {
            // TODO add your handling code here:
            employeeTable.setModel(loadData(""));
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeeView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EmployeeView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSearch;
    private javax.swing.JTable employeeTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables


    private DefaultTableModel loadData(String keyword) throws SQLException {

        List<Employee> employees = ec.searchEmployees(keyword);
        String[] headers = {"No", "Employee ID", "First Name", "Last Name", "Email", "Phone Number", "Hire Date", "Job ID", "Salary", "Commision Percentage", "Manager ID", "Department ID"};
        String[][] employeeCells = new String[employees.size()][12];
        for (int i = 0; i < employeeCells.length; i++) {
            employeeCells[i][0] = (i + 1) + "";
            employeeCells[i][1] = employees.get(i).getId() + "";
            employeeCells[i][2] = employees.get(i).getFirstName();
            employeeCells[i][3] = employees.get(i).getLastName();
            employeeCells[i][4] = employees.get(i).getEmail();
            employeeCells[i][5] = employees.get(i).getPhoneNumber();
            employeeCells[i][6] = employees.get(i).getHireDate() + "";
            employeeCells[i][7] = employees.get(i).getJobId();
            employeeCells[i][8] = employees.get(i).getSalary() + "";
            employeeCells[i][9] = employees.get(i).getCommPct() + "";
            employeeCells[i][10] = employees.get(i).getManagerId() + "";
            employeeCells[i][11] = employees.get(i).getDepartmentId() + "";
        }
        DefaultTableModel dtm = new DefaultTableModel(employeeCells, headers);
        return dtm;
    }
}
